In [1]:
# 导入pandas库
import pandas as pd

In [3]:
# Pandas最基础的数据结构是Series，用来表达一行数据，可理解为一维数组
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
# Pandas另一个关键的数据结构为DataFrame，表示的是二维数组。
# DataFrame中的数据实际是用Numpy的array对象来保存的
import numpy as np
df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))
print(df)
print(df.values) # 查看原始数据

          A         B         C         D
0  1.229850  0.432930  1.191666 -0.956145
1 -0.045065 -1.886596  1.654735  1.707580
2  1.322683  0.731660  0.924832  1.218540
3 -1.039336  1.870142  1.578385  0.325420
4 -0.114580 -0.872958 -0.079647  0.153064
5 -0.371607 -0.540762  0.071397 -1.037617
[[ 1.22985029  0.43293036  1.19166619 -0.95614549]
 [-0.04506463 -1.88659559  1.65473498  1.70758004]
 [ 1.32268328  0.73165994  0.92483198  1.21854016]
 [-1.03933618  1.87014204  1.57838469  0.3254195 ]
 [-0.11458039 -0.87295823 -0.07964704  0.15306435]
 [-0.37160656 -0.54076167  0.07139739 -1.03761697]]


In [9]:
print(df.iloc[0])  #行索引
print(df.A)  #列索引

A    1.229850
B    0.432930
C    1.191666
D   -0.956145
Name: 0, dtype: float64
0    1.229850
1   -0.045065
2    1.322683
3   -1.039336
4   -0.114580
5   -0.371607
Name: A, dtype: float64


In [10]:
df.shape

(6, 4)

In [11]:
df.head()

A         B         C         D
0  1.229850  0.432930  1.191666 -0.956145
1 -0.045065 -1.886596  1.654735  1.707580
2  1.322683  0.731660  0.924832  1.218540
3 -1.039336  1.870142  1.578385  0.325420
4 -0.114580 -0.872958 -0.079647  0.153064

In [12]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [13]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [14]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.163658 -0.044264  0.890228  0.235140
std    0.931106  1.328319  0.743133  1.112575
min   -1.039336 -1.886596 -0.079647 -1.037617
25%   -0.307350 -0.789909  0.284756 -0.678843
50%   -0.079823 -0.053916  1.058249  0.239242
75%    0.911122  0.656978  1.481705  0.995260
max    1.322683  1.870142  1.654735  1.707580

In [16]:
# 数据排序
df.sort_index(axis=1,ascending=False)  #根据列名逆序排列

D         C         B         A
0 -0.956145  1.191666  0.432930  1.229850
1  1.707580  1.654735 -1.886596 -0.045065
2  1.218540  0.924832  0.731660  1.322683
3  0.325420  1.578385  1.870142 -1.039336
4  0.153064 -0.079647 -0.872958 -0.114580
5 -1.037617  0.071397 -0.540762 -0.371607

In [17]:
df.sort_values(by='B')  #根据B列的值进行排序

A         B         C         D
1 -0.045065 -1.886596  1.654735  1.707580
4 -0.114580 -0.872958 -0.079647  0.153064
5 -0.371607 -0.540762  0.071397 -1.037617
0  1.229850  0.432930  1.191666 -0.956145
2  1.322683  0.731660  0.924832  1.218540
3 -1.039336  1.870142  1.578385  0.325420

In [18]:
df[3:5]

A         B         C         D
3 -1.039336  1.870142  1.578385  0.325420
4 -0.114580 -0.872958 -0.079647  0.153064

In [20]:
df[['A','D']]    # 存疑？？？

A         D
0  1.229850 -0.956145
1 -0.045065  1.707580
2  1.322683  1.218540
3 -1.039336  0.325420
4 -0.114580  0.153064
5 -0.371607 -1.037617