本文件夹下的开发环境均为Mac-M1，PyCharm2023，Anaconda3

# 先进行Numpy的学习

In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.array([[1,2],[3,4],[5,6]])
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
# ndim属性查看numpy数组维度
print(a.ndim)
print(b.ndim)
# shape属性查看numpy数组形状
print(a.shape)
print(b.shape)
# dtype属性查看numpy数组类型
print(a.dtype)
print(b.dtype)

1
2
(4,)
(3, 2)
int64
int64


In [6]:
c=np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
d=np.linspace(0,2,11)  #[0,2]被分成11等份
print(d)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [8]:
e = np.ones((3,3))
print (e)
f = np.zeros((3,3))
print (f)
g = np.eye(3)
print (g)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
h = np.random.randn(3,3)  #randn是产生符合正态分布N(0,1)的数
print(h)
i = np.random.randint(10,20,6)  #在[10,20)内产生6个随机数
print(i)
j = np.random.rand(3,3)   #rand是产生[0,1)的数
print(j)

[[-0.11808501 -0.27208862 -0.19798472]
 [ 1.17097244 -0.30092972 -1.05516431]
 [ 0.95741412  1.38218005 -1.15906491]]
[17 14 13 15 19 16]
[[0.06799353 0.05189722 0.39565245]
 [0.21733946 0.27253145 0.46328512]
 [0.21901024 0.75669662 0.65494537]]


In [10]:
k =h * j      #矩阵对应元素相乘
print(k)
l=np.dot(h,j)  #矩阵内积
print(l)

[[-0.00802902 -0.01412064 -0.07833314]
 [ 0.25449852 -0.08201281 -0.48884192]
 [ 0.2096835   1.04589097 -0.7591242 ]]
[[-0.11052529 -0.23009536 -0.30244441]
 [-0.21687714 -0.81968186 -0.36719313]
 [ 0.11165315 -0.45068584  0.26002249]]


In [24]:
#axis表示坐标轴，0表示按行计算，1表示按列计算
m = h.sum(axis=0)
n = h.sum(axis=1)
o = h.sum()
print(m,n,o)
print('最大值：',m.min())
print('最小值',m.max())
print('argumentMin:', m.argmin())  #argmin表示使目标函数f(x)取最小值时的变量值
print('std:',m.std())

p = np.random.randn(10) #会发现，数据量越大，越符合N(0,1)的正态分布
print(p.std(),p.mean())
q = np.random.randn(20000000) #会发现，数据量越大，越符合N(0,1)的正态分布
print(q.std(),q.mean())

[ 2.01030156  0.80916171 -2.41221395] [-0.58815836 -0.18512159  1.18052926] 0.40724931648715024
最大值： -2.4122139465663706
最小值 2.01030155611415
argumentMin: 2
std: 1.8672213881036261
0.8456842084072672 0.1060763790228724
0.9999520626337722 -0.0003165189203324804


In [11]:
# 留一个随机漫步算法作为后期提高

