In [1]:
import pandas as pd

In [3]:
# Pandas最基础的数据结构是Series，用来表达一行数据，可理解为一维数组
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
# Pandas另一个关键的数据结构为DataFrame，表示的是二维数组。
# DataFrame中的数据实际是用Numpy的array对象来保存的
import numpy as np
df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))
print(df)
print(df.values) # 查看原始数据

          A         B         C         D
0  1.229850  0.432930  1.191666 -0.956145
1 -0.045065 -1.886596  1.654735  1.707580
2  1.322683  0.731660  0.924832  1.218540
3 -1.039336  1.870142  1.578385  0.325420
4 -0.114580 -0.872958 -0.079647  0.153064
5 -0.371607 -0.540762  0.071397 -1.037617
[[ 1.22985029  0.43293036  1.19166619 -0.95614549]
 [-0.04506463 -1.88659559  1.65473498  1.70758004]
 [ 1.32268328  0.73165994  0.92483198  1.21854016]
 [-1.03933618  1.87014204  1.57838469  0.3254195 ]
 [-0.11458039 -0.87295823 -0.07964704  0.15306435]
 [-0.37160656 -0.54076167  0.07139739 -1.03761697]]


In [9]:
print(df.iloc[0])  #行索引
print(df.A)  #列索引

A    1.229850
B    0.432930
C    1.191666
D   -0.956145
Name: 0, dtype: float64
0    1.229850
1   -0.045065
2    1.322683
3   -1.039336
4   -0.114580
5   -0.371607
Name: A, dtype: float64
