In [1]:
import torch

In [6]:
x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [8]:
X = x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [12]:
torch.zeros(2,3,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [13]:
# 创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。
torch.randn(3,4)

tensor([[-0.7213,  0.6363,  0.8618,  0.9637],
        [-0.2665, -1.6698, -0.5074,  1.9321],
        [ 0.6017, -1.8173, -0.6905,  0.7957]])

In [15]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [16]:
print(x[1:3])  #切片

tensor([1, 2])


In [22]:
print(id(X))
X = X+torch.ones(X.shape)
print(id(X))
# 易发现，内存变化了。
# 执行原地操作非常简单，可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>
Z = torch.zeros_like(X)
print('id(Z):',id(Z))
Z[:] = X + torch.zeros_like(X)
print("id(Z):",id(Z))

5184572112
5182502096
id(Z): 5182504112
id(Z): 5182504112


In [24]:
# numpy 与张量互相转换
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 2.2 数据预处理

In [26]:
# 读取数据集
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [33]:
import pandas as pd

data = pd.read_csv(data_file)
print(data,end='\n\n')
print(data.shape)
print(data.values)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

(4, 3)
[[nan 'Pave' 127500]
 [2.0 nan 106000]
 [4.0 nan 178100]
 [nan nan 140000]]


In [78]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
numeric_inputs = data.select_dtypes(include='number')
mean_value = numeric_inputs.mean()
inputs = inputs.fillna(mean_value)
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
