In [1]:
import torch

In [6]:
x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [8]:
X = x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [12]:
torch.zeros(2,3,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [13]:
# 创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样。
torch.randn(3,4)

tensor([[-0.7213,  0.6363,  0.8618,  0.9637],
        [-0.2665, -1.6698, -0.5074,  1.9321],
        [ 0.6017, -1.8173, -0.6905,  0.7957]])

In [15]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [16]:
print(x[1:3])  #切片

tensor([1, 2])


In [22]:
print(id(X))
X = X+torch.ones(X.shape)
print(id(X))
# 易发现，内存变化了。
# 执行原地操作非常简单，可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>
Z = torch.zeros_like(X)
print('id(Z):',id(Z))
Z[:] = X + torch.zeros_like(X)
print("id(Z):",id(Z))

5184572112
5182502096
id(Z): 5182504112
id(Z): 5182504112


In [24]:
# numpy 与张量互相转换
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 2.2 数据预处理

In [26]:
# 读取数据集
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [33]:
import pandas as pd

data = pd.read_csv(data_file)
print(data,end='\n\n')
print(data.shape)
print(data.values)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

(4, 3)
[[nan 'Pave' 127500]
 [2.0 nan 106000]
 [4.0 nan 178100]
 [nan nan 140000]]


In [78]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
numeric_inputs = data.select_dtypes(include='number')
mean_value = numeric_inputs.mean()
inputs = inputs.fillna(mean_value)
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [81]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [90]:
A.T   # 转置矩阵

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [93]:
A == A.T # 不等大不可执行

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [88]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [89]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [100]:
C = torch.arange(16).reshape(4,4)
C == C.T

/var/folders/3v/5ms4svfn01vc94jb5tbtdw400000gn/T/ipykernel_33819/419714116.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3618.)
  C == C.T


RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [102]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print(A)
print(A+B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


In [105]:
# 两个矩阵的按元素乘法称为Hadamard积（Hadamard product)
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [106]:
A * B + 100

tensor([[100., 101., 104., 109.],
        [116., 125., 136., 149.],
        [164., 181., 200., 221.],
        [244., 269., 296., 325.],
        [356., 389., 424., 461.]])

In [111]:
print(A)
print(A.shape)
print(A.sum())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])
tensor(190.)


In [114]:
A_sum_axis0 = A.sum(axis=0)   # 以行为单位 axis=0
print(A_sum_axis0)

B_sum_axis1 = B.sum(axis=1)   # 以列为单位，对行进行求和 axis=0
print(B_sum_axis1)

tensor([40., 45., 50., 55.])
tensor([ 6., 22., 38., 54., 70.])
